name: caldera
recipe: wordpress
config:
  env: dev
  xdebug: true
  php: '7.2'
  via: nginx
  webroot: wordpress
proxy:
  mailhog:
  - mail.caldera.lndo.site
  pma:
  - pma.caldera.lndo.site
  node:
  - app.lndo.site
services:
  appserver:
    composer:
      phpunit/phpunit: '*'
    build:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-build.sh"
    post-start:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-start.sh"
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
    - database
    - database.caldera.internal
  node:
    type: node:9
    ssl: true
    overrides:
      services:
        ports:
        - "3000:3000"
    run:
    - "cd $LANDO_MOUNT && yarn && yarn build && yarn start"
tooling:
  yarn:
    service: node
  node:
    service: node
  composer:
    service: appserver
  wp:
    service: appserver

