name: caldera
recipe: wordpress
config:
  env: dev
  xdebug: true
  php: '7.2'
  via: nginx
  webroot: wordpress
proxy:
  mailhog:
  - mail.caldera.lndo.site
  pma:
  - pma.caldera.lndo.site
services:
  appserver:
    composer:
      phpunit/phpunit: '*'
    build:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-build.sh"
    - "bash ./scripts/wp/install-wp-tests.sh wordpress wordpress wordpress database"
    post-start:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-start.sh"
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
    - database
    - database.caldera.internal
  wptest:
    type: php:custom
    overrides:
      services:
        image: chriszarate/wordpress-phpunit
    volumes:
        - .:/app
        - testsuite:/tmp
tooling:
  app:
    description: "Start app front-end"
    cmd: "cd $LANDO_MOUNT && cd js-packages/app && yarn start"
    service: node
  composer:
    service: appserver
  wp:
    service: appserver
  wptests:
    service: wptest
    description: Runs WordPress tests
    cmd: "phpunit"
    user:  root
  wptests-i:
    service: wptest
    description: Installs WordPress tests
    cmd: "cd $LANDO_MOUNT && bash scripts/wp/install-wp-tests.sh wordpress wordpress wordpress database"
    user:  root
  dbTests:
    service: wptest
    description: Runs calderawp/caldera-db tests using main container
    cmd: "cd $LANDO_MOUNT/php-packages/caldera-db && composer test:acceptance"
    user:  root
