<?php


namespace calderawp\caldera\Messaging\Entities;


class EntryData extends Entity
{

	/**
	 * @var MessageEntryFields
	 */
	protected $fields;

	protected $id;
	protected $form_id;
	protected $user_id;
	protected $datestamp;
	protected $status;


	public static function fromArray(array $items): Entity
	{
		if( isset( $items['fields']) && is_array( $items['fields'])){
			$items['fields'] = MessageEntryFields::fromArray($items['fields']);
		}
		return parent::fromArray($items); // TODO: Change the autogenerated stub
	}

	/**
	 * @return MessageEntryFields
	 */
	public function getFields(): MessageEntryFields
	{
		if( empty( $this->fields ) ){
			$this->setFields(new MessageEntryFields());
		}
		return $this->fields;
	}

	/**
	 * @param MessageEntryFields $fields
	 *
	 * @return EntryData
	 */
	public function setFields(MessageEntryFields $fields): EntryData
	{
		$this->fields = $fields;
		return $this;
	}



}
